name: "Git commit"
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "github.actions@snowplane.net"
      - run: git config --global user.name "Snowpusher"
      - run: git branch foo
      - run: echo foo > foo.txt
      - run: git add foo.txt
      - run: git commit -m "Added foo.txt"
      - run: hub pull-request -m "Foo"
