name: Node.js CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  lts_versions:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::$(curl https://fvdm.com/u/nodejs-lts-versions.json)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    needs: lts_versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.lts_versions.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git fetch --prune --unshallow
    - run: npm ci
    - run: npm test
    - run: npm audit
